language: c

sudo: false

env:
  matrix:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)"
  global:
    secure: "rB4Bxk7356tDhwcNBKZorPjPUoTtmg71I/w8Ec/5b+e3ahqj715tL2hd+6woG2/h0CPpVgK0odCU0fm6KLoAlNqejFaytRzqIlMqN2zjIEkZPhy13BmqGHFbJCwgnKOdrQIHN08AiWX8hSPJ+W4jv8iEds5DZL4mYCwv0HHWmns="

addons:
  apt:
    sources:
    - r-packages-precise
    packages:
    - r-base-dev
    - r-recommended

install:
  - "wget -q -O - http://yihui.name/xran/r-config | bash"
  - Rscript -e "if (!require('devtools')) install.packages('devtools')"
  - Rscript -e "devtools::install_deps(dep = TRUE); update.packages(.libPaths()[1], ask = FALSE)"

cache:
  directories:
  - $HOME/R

script:
  - cd ..; rm -f *.tar.gz; R CMD build $R_PKG
  - R CMD check $R_PKG*.tar.gz --no-manual
  - cd $R_PKG

# deploy to XRAN
after_success:
  - "(wget -q -O - http://yihui.name/xran/r-xran | bash)"
